import type { PortfolioData } from "./types";

export const sampleData: PortfolioData = {
  investments: [
    {
      id: "inv-1",
      name: "Indian Railway Finance Corporation Limited",
      symbol: "IRFC",
      type: "Stock",
      units: 100,
      avgPrice: 86.71,
      currentPrice: 86.71,
      demo: true,
    },
    {
      id: "inv-2",
      name: "ITC Hotels Limited",
      symbol: "ITCHOTELS",
      type: "Stock",
      units: 1,
      avgPrice: 651.85,
      currentPrice: 651.85,
      demo: true,
    },
    {
      id: "inv-3",
      name: "ITC Limited",
      symbol: "ITC",
      type: "Stock",
      units: 30,
      avgPrice: 380.01,
      currentPrice: 380.01,
      demo: true,
    },
    {
      id: "inv-4",
      name: "Kaynes Technology India Limited",
      symbol: "KAYNES",
      type: "Stock",
      units: 3,
      avgPrice: 3182,
      currentPrice: 3182,
      demo: true,
    },
    {
      id: "inv-5",
      name: "Nippon India ETF Gold BeES",
      symbol: "GOLDBEES",
      type: "ETF",
      units: 101,
      avgPrice: 103.32,
      currentPrice: 103.32,
      demo: true,
    },
    {
      id: "inv-6",
      name: "PC Jeweller Limited",
      symbol: "PCJEWELLER",
      type: "Stock",
      units: 150,
      avgPrice: 9.28,
      currentPrice: 9.28,
      demo: true,
    },
    {
      id: "inv-7",
      name: "Suzlon Energy Limited",
      symbol: "SUZLON",
      type: "Stock",
      units: 50,
      avgPrice: 60.05,
      currentPrice: 60.05,
      demo: true,
    },
    {
      id: "inv-8",
      name: "Tata Motors Commercial Vehicles Limited",
      symbol: "TMCV",
      type: "Stock",
      units: 50,
      avgPrice: 220.87,
      currentPrice: 483.75,
      demo: true,
    },
    {
      id: "inv-9",
      name: "Tata Motors Passenger Vehicles Limited",
      symbol: "TMPV",
      type: "Stock",
      units: 105,
      avgPrice: 411.13,
      currentPrice: 313.1,
      demo: true,
    },
    {
      id: "inv-10",
      name: "Trident Limited",
      symbol: "TRIDENT",
      type: "Stock",
      units: 100,
      avgPrice: 27.76,
      currentPrice: 27.76,
      demo: true,
    },
    {
      id: "inv-11",
      name: "Ujjivan Small Finance Bank Limited",
      symbol: "UJJIVANSFB",
      type: "Stock",
      units: 75,
      avgPrice: 33.74,
      currentPrice: 33.74,
      demo: true,
    },
  ],
  assets: [
    {
      id: "ast-1",
      name: "Public Provident Fund",
      category: "PPF",
      institution: "SBI",
      invested: 250000,
      currentValue: 268000,
      maturityDate: "2031-03-31",
      interestRate: 7.1,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-2",
      name: "Employee Provident Fund",
      category: "EPF/PF",
      institution: "EPFO",
      invested: 320000,
      currentValue: 341600,
      interestRate: 8.25,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-3",
      name: "LIC Jeevan Anand",
      category: "Insurance",
      institution: "LIC",
      invested: 150000,
      currentValue: 168000,
      maturityDate: "2034-06-15",
      interestRate: 5.5,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-4",
      name: "Salary Savings Account",
      category: "Savings Account",
      institution: "HDFC Bank",
      invested: 100000,
      currentValue: 103000,
      interestRate: 3,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-5",
      name: "Sovereign Gold Bond",
      category: "Gold",
      institution: "RBI",
      invested: 200000,
      currentValue: 246500,
      maturityDate: "2029-08-05",
      interestRate: 2.5,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-6",
      name: "Fixed Deposit 3Y",
      category: "Fixed Deposit",
      institution: "ICICI Bank",
      invested: 250000,
      currentValue: 271250,
      maturityDate: "2027-01-20",
      interestRate: 7.25,
      status: "Active",
      demo: true,
    },
    {
      id: "ast-7",
      name: "NPS Tier-1",
      category: "NPS",
      institution: "HDFC Pension",
      invested: 180000,
      currentValue: 214300,
      maturityDate: "2048-04-01",
      interestRate: 10.2,
      status: "Active",
      demo: true,
    },
  ],
};
